// Build Film's "Drawn" people (web/film/peeps.mjs) from Open Peeps, docs/film-plan.md.
//
//   PEEPS_DIR=<react-peeps package dir> node scripts/film/build-peeps.mjs web/film/peeps.mjs
//
// Needs, installed somewhere on NODE_PATH (not in this repo): react@18,
// react-dom@18, svgpath, svg-path-bbox — and the react-peeps package itself
// (npm pack react-peeps@0.1.10; MIT, Emre Çakır), whose pieces are Pablo
// Stanley's Open Peeps (CC0). Each chosen piece is rendered to SVG with two
// marker colours, its paths' translations are baked in and rounded to 0.1,
// and every fill becomes 0 = ink or 1 = paper, so the page picks the colours.
// The page draws them with Path2D: no SVG, no images, nothing fetched at play.
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
const require = createRequire(import.meta.url);
const React = require("react"), { renderToStaticMarkup } = require("react-dom/server");
const svgpath = require("svgpath"), { svgPathBbox } = require("svg-path-bbox");

const dir = process.env.PEEPS_DIR, out = process.argv[2];
if (!dir || !out) { console.error("usage: PEEPS_DIR=<react-peeps> node scripts/film/build-peeps.mjs <out.mjs>"); process.exit(1); }
const lib = join(dir, "lib/peeps");
const opt = p => require(join(lib, p, "z_options.js"));
const { StandingPose } = opt("pose/standing"), { SittingPose } = opt("pose/sitting");
const { Face } = opt("face"), { Hair } = opt("hair"), { FacialHair } = opt("facialHair"), { Accessories } = opt("accessories");

// Two outfits that hold across every pose: BW = dark top, light trousers; WB = the reverse.
const POSES = ["RestingBW", "RestingWB", "PointingFingerBW", "PointingFingerWB", "CrossedArmsBW", "CrossedArmsWB", "WalkingBW", "WalkingWB",
  "RoboDanceBW", "RoboDanceWB", "MediumBW", "MediumWB", "HandsBackBW", "HandsBackWB", "OneLegUpBW", "OneLegUpWB", "CrossedLegs"];
const FACES = ["Calm", "Smile", "SmileBig", "Serious", "Solemn", "Concerned", "Explaining", "Awe", "EyesClosed", "Angry", "VeryAngry", "Fear",
  "Cheeky", "Suspicious", "Tired", "Driven", "Contempt", "SmileTeeth", "Blank", "Hectic", "LoveGrin"];
const HAIRS = ["Afro", "Bald", "BaldSides", "BaldTop", "Bangs", "BantuKnots", "Bun", "BunCurly", "Buns", "CornRows", "FlatTop", "GrayBun", "GrayMedium",
  "GrayShort", "Hijab", "Long", "LongAfro", "LongCurly", "Medium", "MediumBangs", "MediumLong", "MediumShort", "MediumStraight", "Pomp",
  "ShavedSides", "Short", "ShortCurly", "ShortWavy", "Turban", "Twists"];
const BEARDS = ["Chin", "Full", "FullMedium", "Goatee", "GrayFull", "Handlebars", "MoustacheThin"];
const GLASSES = ["GlassRound", "GlassAviator", "GlassClubmaster", "SunglassWayfarer"];

const INK = "#000001", PAPER = "#fffffe";
function piece(Component, [ox, oy] = [0, 0]) {
  const svg = renderToStaticMarkup(React.createElement(Component, { strokeColor: INK, backgroundColor: PAPER }));
  const stack = [[ox, oy]], paths = [];
  let box = [Infinity, Infinity, -Infinity, -Infinity];
  for (const [, close, tag, attrs, self] of svg.matchAll(/<(\/?)(\w+)([^>]*?)(\/?)>/g)) {
    if (close) { if (tag === "g") stack.pop(); continue; }
    const a = Object.fromEntries([...attrs.matchAll(/([\w-]+)="([^"]*)"/g)].map(m => [m[1], m[2]]));
    const [px, py] = stack.at(-1);
    const tr = /translate\(([-\d.e]+)[ ,]+([-\d.e]+)\)/.exec(a.transform || "");
    const [x, y] = tr ? [px + +tr[1], py + +tr[2]] : [px, py];
    if (tag === "g" && !self) stack.push([x, y]);
    if (tag !== "path" || !a.d || a.fill === "none") continue;
    // A piece's own colour (a lens tint) stays as it is.
    const fill = a.fill === INK ? 0 : a.fill === PAPER || /^#fff(fff)?$/i.test(a.fill) ? 1 : a.fill.toLowerCase();
    const d = svgpath(a.d).translate(x, y).round(1).toString();
    const b = svgPathBbox(d);
    box = [Math.min(box[0], b[0]), Math.min(box[1], b[1]), Math.max(box[2], b[2]), Math.max(box[3], b[3])];
    paths.push([typeof fill === "number" ? fill + (a["fill-rule"] === "evenodd" ? 2 : 0) : fill, d]);
  }
  return { box: box.map(v => Math.round(v)), paths };
}
const all = (names, table, at) => Object.fromEntries(names.map(n => { if (!table[n]) throw new Error(`no piece ${n}`); return [n, piece(table[n], at)]; }));
// Where react-peeps puts each head piece: its Head component shifts the whole head by
// (225, 0), then each piece by its own offset. Missing the first put every head off its neck.
const data = {
  poses: all(POSES, { ...StandingPose, ...SittingPose }),
  hair: all(HAIRS, Hair, [225, 0]), faces: all(FACES, Face, [225 + 159, 186]), beards: all(BEARDS, FacialHair, [225 + 123, 338]), glasses: all(GLASSES, Accessories, [225 + 47, 241]),
};
const js = `// Generated by scripts/film/build-peeps.mjs — never edit by hand.
// Open Peeps by Pablo Stanley (CC0), as packaged by react-peeps (MIT, (c) 2020-present Emre Çakır).
// Each piece: { box: [x0, y0, x1, y1], paths: [[kind, d]] }, kind 0 ink, 1 paper, +2 even-odd, or a colour of its own.
export const PEEPS = ${JSON.stringify(data)};
`;
writeFileSync(out, js);
for (const [k, v] of Object.entries(data)) console.log(k, Object.keys(v).length, (JSON.stringify(v).length / 1024).toFixed(0) + " KB");
console.log(`${out}: ${(js.length / 1024).toFixed(0)} KB`);
